### ISSUE TITLE
Error: [$injector:strictdi] function($scope, $element) is not using explicit annotation and cannot be invoked in strict mode

### ISSUE THREAD

**Issue by albertosantini** [4rlekin/ng-simple-modal#10]
Using `ng-strict-di`, as `<html lang="en" ng-app="root" ng-strict-di>`, I get the following error:

`Error: [$injector:strictdi] function($scope, $element) is not using explicit annotation and cannot be invoked in strict mode`

Fixed with

```
            this.controller = function($scope, $element) {
...
            }
            this.controller.$inject = ["$scope", "$element"];
...
```

If it looks good to you, I may prepare a PR.

Repro test: https://plnkr.co/edit/q6CrW1ksq2ZTNx3hbnlg?p=preview
Click on the button to raise the error.

**Comment by mswiecicki** [comment]
Sure, it is best practice (ie. the most readable imho) anyway.

I'd be very thankful for PR

**Comment by albertosantini** [comment]
It seems with Angular 6 out there, coding for AngularJS is a bit weirdly. :)
