### ISSUE TITLE
Usage in ES2015 context

### ISSUE THREAD

**Issue by albertosantini** [4rlekin/ng-simple-modal#11]
This is a just a note. Maybe to copy back to README.

'ng-simple-modal' is written in ES2105 and it is published via `IIFE`, loading the source with a scripts tag.

How to use `ng-simple-modal` in a ES2015 environment, intending via `import`, bundling the source with webpack or rollup?

For instance, in `app.module.js` we can add the dependency:
```
import angular from "angular";
import uiRouter from "angular-ui-router";
// to insert the dep in the bundle, even if simpleModal is not used
import simpleModal from "ng-simple-modal"; 


import { appComponent } from "./app.component";

export const app = angular
    .module("common.app", [
        uiRouter,
        // here it would be better using simpleModal, like uiRouter, but you can't
        "simple-modal"
    ])
    .component("app", appComponent)
    .config(config)
    .name;
...
```

Then in app.controller.js` we can use the modal service:
```
class AppController {
    constructor(modalService) {
        this.modalService = modalService;
    }

    $onInit() {
        const modalConfig = {
            template: `
                <div class="modalContents">
                    <button ng-click="closeModal()">Close</button>
                </div>`
        };

        this.modalService.open(modalConfig);
    }
}
AppController.$inject = ["modalService"];

export { AppController };
```

The user code is bundled as usual with webpack or rollup (or whatever bundler), resolving accordingly the imports. 

I could not find a viable solution to resolve `"simple-modal"` vs. `simpleModal` in the dependency use: I think that is resolved using a build step exporting the name.

```
export const SimpleModal= angular
  .module("simple-module", [
    ...
  ])
...
  .name;
```

**Comment by mswiecicki** [comment]
I was just wondering - since i recently started using webpack if i should change it to more modern approach.

I think that still many people don't use webpack, but then again, since i wanted to be so hip and modern and all ES2015 i guess i should make it webpack ready.

**Comment by albertosantini** [comment]
Following Universal Module Definition ([UMD](https://github.com/umdjs/umd)), you can publish the lib supporting all the worlds: AMD, CJS, global and ES6 module.

The pattern is the following one:
```
(function (root, factory) {
    if (typeof define === 'function' && define.amd) {
        // AMD. Register as an anonymous module.
        define(["exports"], factory);
    } else if (typeof module === 'object' && module.exports) {
        // Node. Does not work with strict CommonJS, but
        // only CommonJS-like environments that support module.exports,
        // like Node.
        module.exports = factory();
    } else {
        // Browser globals (root is window)
        root.returnExports = factory();
    }
}(this, function () {
    const simpleModal = angular
        .module('simple-modal', [])
        .config(['$compileProvider', function($compileProvider){
            cachedCompileProvider = $compileProvider;
        }])
        .factory('modalService', modalService)
        .name;
...
   return simpleModal;
}));
```

And its usage:
```
import simpleModal from "ng-simple-modal";
...
export const app = angular
    .module("common.app", [
        uiRouter,
        simpleModal
    ])
    .component("app", appComponent)
    .config(config)
    .name;
...
```

Tested with webpack, rollup in ES2015 bundler context and with the usual ES5 scripts tag.

Preparing a PR: if it makes sense and it looks good to you, you can merge it.

**Comment by albertosantini** [comment]
It seems with Angular 6 out there, coding for AngularJS is a bit weirdly. :)
