### ISSUE TITLE
Pass an answer when closing

### ISSUE THREAD

**Issue by albertosantini** [4rlekin/ng-simple-modal#7]
What if the modal contains some user input (a form or whatever) and when the modal is closed I need that info?

I would pass that info to the `closeModal`:

```
        let modalConfig = {
            template: `
                <div class="modalContents">
                    <input ng-model="username"><br/>
                    
                    <button ng-click="closeModal({username: username})">Close</button>
                </div>`,
            onClose: function(answer) {
                alert(answer.username);
            }
        };
```

And in the source, we need the following change:
```
                $scope.closeModal = function closeModal(answer) {
                    scopeObj._onClose(answer);
                    $scope.$destroy();
                    $element.remove();
                };
```

Live example: https://plnkr.co/edit/eM8QBrmPvkRGQo3O4PZV?p=preview

If it makes sense, I would prepare a PR.

**Comment by mswiecicki** [comment]
That obviously makes a lot of sense - so far the assumed method of getting info from modal was passing object on scope (which is kinda suboptimal).

I'd love a PR from you - though fair warning - it will be my first PR as an owner of repo, so it might be a little bumpy affair.

Only one thing i'd like to bring up here - the "internal" method for closing modal by clicking on backdrop uses the same `onClose` method; and while there is no reason not to leave it as it is, i wonder if there is any legitimate use case that would call for passing data back on backdrop closing.

**Comment by albertosantini** [comment]
When the user clicks on the backdrop to cancel the dialog, the answer is `undefined` and the developer can accordingly code the correct action, submit or cancel.

For instance, this is my use case with material:

```
<md-dialog-content layout="column" layout-align="center center" layout-margin layout-padding>
    <md-subheader class="md-sticky-no-effect">Token Dialog</md-subheader>

    <md-radio-group layout="row" ng-model="$ctrl.environment">
        <md-radio-button value="practice">Practice</md-radio-button>
        <md-radio-button value="live">Live</md-radio-button>
    </md-radio-group>

    <md-input-container ng-if="$ctrl.environment === 'practice' || $ctrl.environment === 'live'">
        <label>Token</label>
        <input ng-model="$ctrl.token">
    </md-input-container>

</md-dialog-content>

<md-dialog-actions layout="row">
    <span flex></span>
    <md-button ng-click="$ctrl.answer()">
        Reset
    </md-button>
    <md-button ng-click="$ctrl.answer({'environment': $ctrl.environment, 'token': $ctrl.token})" class="md-primary">
        Ok
    </md-button>
</md-dialog-actions>
```

As you see, `$ctrl.answer()` vs. `$ctrl.answer({...})`, intending `reset/cancel` vs. `submit` case.

Edit - I modified the plunker above to show what I said:

```
            onClose: function(answer) {
                if (answer) {
                  alert(answer.username);
                }
            }
```

**Comment by albertosantini** [comment]
It seems with Angular 6 out there, coding for AngularJS is a bit weirdly. :)
