### ISSUE TITLE
Live examples

### ISSUE THREAD

**Issue by albertosantini** [4rlekin/ng-simple-modal#8]
I would add a section in the README containing live examples, after `Usage` section:

```
##Live examples:

- [Simplest possible](https://plnkr.co/edit/s6qSGV16pVgSxBuBPJGL?p=preview)
- [With onClose callback](https://plnkr.co/edit/t5UCOnqNSIiOUNr4UFHM?p=preview)
```

If you are agree, I would prepare a PR.

**Comment by mswiecicki** [comment]
That would be great!

Should we then drop the `examples` folder from repo ?

**Comment by albertosantini** [comment]
There are pros and cons to remove the examples folder.
The examples contain the main usage references and they don't depend on external resources.
What if plunker is down?

A tradeoff would be adding the relevant code in the README with live link, deleting examples folder.

---
## Examples

The developer needs to style the modal.

For instance,

```
    <style>
        .modalContents {
            min-width: 400px;
            min-height: 200px;
            background-color: white;
            border: 1px solid #cccccc;
            display: flex;
            justify-content: center;
            align-items: center;
        }
    </style>
```

Simplest possible example:
```
            $scope.openModal = function openModal() {
                let modalConfig = {
                    template: `
                        <div class="modalContents">
                            <button ng-click="closeModal()">Close</button>
                        </div>`
                };
                modalService.open(modalConfig);
            }
```
Live link: [Simplest possible](https://plnkr.co/edit/s6qSGV16pVgSxBuBPJGL?p=preview)

---

So it would be easily reproduce a new example in the fatal event the plunker is lost.

At the moment the PR adds only the links.
Maybe you may give a second look at this proposal and decide later.

**Comment by albertosantini** [comment]
It seems with Angular 6 out there, coding for AngularJS is a bit weirdly. :)
