### ISSUE TITLE
tags and npm versions 

### ISSUE THREAD

**Issue by albertosantini** [4rlekin/ng-simple-modal#9]
Just a suggestion.
Usually npm versions are in sync with git tags.

In npm:
```
     created: '2017-01-12T11:01:41.325Z',
     '1.0.0': '2017-01-12T11:01:41.325Z',
     '1.0.1': '2017-01-12T11:11:04.052Z',
     '1.0.2': '2017-01-13T09:33:43.946Z',
     '1.0.3': '2017-01-16T09:52:22.190Z',
     '1.1.0': '2017-01-17T19:21:55.430Z',
     '1.0.4': '2017-01-17T19:22:29.702Z',
     '1.1.1': '2017-01-18T09:37:32.564Z',
     '1.1.2': '2017-02-06T10:14:47.023Z' },
```

Tags in master:
```
v1.0.0
v1.1.0
```

**Comment by mswiecicki** [comment]
Well, this repo is literally 100% of my experience with npm publishing and i messed things up along the way.

If there is a way to fix that i'd be very grateful - for instance i wouldn't even know how to acquire such a list (the npm one not the git obviously).

**Comment by albertosantini** [comment]
You can see the npm details with the command: `npm view ng-simple-modal`:

```
$ npm view ng-simple-modal

{ name: 'ng-simple-modal',
  description: 'Barebones, unopinionated modal service for angularjs 1.X written in ES2015',
  'dist-tags': { latest: '1.1.2' },
  versions: [ '1.0.0', '1.0.1', '1.0.2', '1.1.1', '1.1.2' ],
  maintainers: [ '4rlekin <marekswiecicki@protonmail.com>' ],
  time:
   { modified: '2017-02-06T10:14:47.023Z',
     created: '2017-01-12T11:01:41.325Z',
     '1.0.0': '2017-01-12T11:01:41.325Z',
     '1.0.1': '2017-01-12T11:11:04.052Z',
     '1.0.2': '2017-01-13T09:33:43.946Z',
     '1.0.3': '2017-01-16T09:52:22.190Z',
     '1.1.0': '2017-01-17T19:21:55.430Z',
     '1.0.4': '2017-01-17T19:22:29.702Z',
     '1.1.1': '2017-01-18T09:37:32.564Z',
     '1.1.2': '2017-02-06T10:14:47.023Z' },
  homepage: 'https://github.com/4rlekin/ng-simple-modal#readme',
  keywords: [ 'modal', 'dialog', 'popup', 'alert', 'ng', 'angularjs', 'angular' ],
  repository:
   { type: 'git',
     url: 'git+https://github.com/4rlekin/ng-simple-modal.git' },
  author: 'Marek Święcicki 2017',
  bugs: { url: 'https://github.com/4rlekin/ng-simple-modal/issues' },
  license: 'MIT',
  readmeFilename: 'README.md',
  version: '1.1.2',
  main: 'simple-modal.js',
  scripts: { test: 'echo "still no tests..."' },
  gitHead: 'e4038f7a18a7957a84d032214681699932f17545',
  dist:
   { shasum: 'f79b9384e062b01914c2ec5ac7fa772444233bbc',
     tarball: 'https://registry.npmjs.org/ng-simple-modal/-/ng-simple-modal-1.1.2.tgz' },
  directories: {} }
```

I have been following these formal steps when I need to release the version v1.2.3:

- npm test
- change the version of package.json
- run changelog
- commit changelog with message `docs(CHANGELOG): v1.2.3`
- commit package.json with message `chore(release): v1.2.3`
- git tag v1.2.3
- git push
- git push --tags
- npm publish

Of course the workflow depends on the project and your mileage may vary.

For instance, instead of handling a CHANGELOG, a few projects prefer to fill a GitHub release.
There are also utils to automate those steps.

Edit: a correct sync between npm and repo helps to identify the source associate to a version or to provide a version via cdn, forn instance rawgit or unpkg.
